'use client'

import { Search } from 'lucide-react'
import { FormEvent, useTransition } from 'react'
import { usePathname, useRouter } from 'next/navigation'
import type { Composer } from '../../lib/db/composers'

export default function ComposerDirectory({ composers, search }: { composers: Composer[]; search: string }) {
  const router = useRouter(), pathname = usePathname() ?? '/', [pending, startTransition] = useTransition()
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const value = String(new FormData(event.currentTarget).get('search') || '').trim(); startTransition(() => router.push(value ? `${pathname}?search=${encodeURIComponent(value)}` : pathname)) }
  return <><form onSubmit={submit} className="flex max-w-xl gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><label className="relative flex-1"><span className="sr-only">Search composers</span><span className="pointer-events-none absolute left-3 top-2.5 text-slate-400"><Search size={16} aria-hidden="true" /></span><input name="search" defaultValue={search} placeholder="Search composers…" className="h-10 w-full rounded-xl border border-slate-200 bg-slate-50 pl-9 pr-3 text-sm outline-none focus:border-blue-500 focus:ring-4 focus:ring-blue-100" /></label><button className="rounded-xl bg-blue-600 px-4 text-sm font-semibold text-white hover:bg-blue-700" type="submit">{pending ? 'Searching…' : 'Search'}</button></form><div className="mt-5 flex justify-between text-sm text-slate-500"><span>{composers.length} composers</span><span>Page 1 of 1</span></div><div className="mt-3 grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{composers.map(composer => <a key={composer.artistId} href={`/composers/${composer.slug}`} className="group flex min-w-0 gap-4 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm hover:border-blue-300 hover:shadow-md"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl bg-blue-50 text-base font-semibold text-blue-700">{composer.name.slice(0, 1)}</div><div className="min-w-0"><h2 className="heading truncate text-base font-semibold text-slate-950 group-hover:text-blue-700">{composer.name}</h2><p className="mt-1 line-clamp-2 text-sm leading-5 text-slate-500">{composer.biography || 'No introduction available.'}</p></div></a>)}</div>{!composers.length && <div className="mt-3 rounded-2xl border border-slate-200 bg-white px-6 py-14 text-center text-sm text-slate-500">No composers match this search.</div>}</>
}
